# Generated by Django 3.2.5 on 2021-07-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
