GENDER_MALE = "MALE"
GENDER_FEMALE = "FEMALE"
GENDER_OTHER = "OTHER"

GENDER_CHOICES = [
    (GENDER_MALE, "MALE"),
    (GENDER_FEMALE, "FEMALE"),
    (GENDER_OTHER, "OTHER"),
]


CURRENCY_USD = "USD"
CURRENCY_KRW = "KRW"

CURRENCY_CHOICES = [
    (CURRENCY_USD, "USD"),
    (CURRENCY_KRW, "KRW"),
]

LANGUAGE_EN = "EN"
LANGUAGE_KR = "KR"

LANGUAGE_CHOICES = [
    (LANGUAGE_EN, "US"),
    (LANGUAGE_KR, "KR"),
]
